# Generated by Django 4.2.20 on 2025-07-23 11:54

from django.db import migrations
from django.utils.text import slugify


def forward_code(apps, schema_editor):
    Song = apps.get_model("hottrack", "Song")
    qs = Song.objects.filter(slug="")
    for song in qs:
        # 마이그레이션에서는 모델의 커스텀 메서드를 사용할 수 없습니다.
        # 마이그레이션에서는 모델 필드만 직렬화하기 때문입니다.
        song.slug = slugify(song.name, allow_unicode=True)
    Song.objects.bulk_update(qs, ["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("hottrack", "0002_song_slug_song_hottrack_so_slug_7cf104_idx"),
    ]

    operations = [
        migrations.RunPython(forward_code, reverse_code=migrations.RunPython.noop),
    ]
